### ISSUE TITLE
Stratigraphy's layers visibility configuration

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#30]
Applying changes in the "Settings" > "Editor" > "Stratigraphy form fields" it affetcs the viewer page, but does not affect the "show all" feature in editor > stratigraphy > layer details

![image](https://user-images.githubusercontent.com/1797931/174618179-a3645812-59d0-43d0-9189-1a8a9852a706.png)

**Comment by malihgh** [comment]
Some Stratigraphy fields remain to add to server + these two fields in Editor and Viewer are the same and even they are sink but we should create Viewer (that is new), separated from Editor.
