### ISSUE TITLE
Viewer "QC depth" label wrong

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#32]
Replace the label from dict "qt_length" with "totaldepth" in viewer > borehole details:

![image](https://user-images.githubusercontent.com/1797931/174621508-e416997c-2246-4bab-8c94-420688830e19.png)

**Comment by malihgh** [comment]
![Screenshot 2022-06-20 at 16-24-11 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/174623488-1a2ba1b2-a693-4d04-a98d-cbe2c5f876c5.png)

**Comment by malihgh** [comment]
![Screenshot 2022-07-24 at 10-38-14 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/180639286-01d0caed-158f-4e5b-b67a-7eafb04e0f68.png)
