### ISSUE TITLE
New search fields for completion profiles

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#38]
Recently we have added new profile kinds (Completion). There some new fields that have to be added to the search feature in Viewer and Editor mode.

**Comment by malihgh** [comment]
![Screenshot 2022-07-15 at 14-48-06 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/179226059-1eb57d45-9379-4f5a-9787-82106c3db159.png)

**Comment by malihgh** [comment]
@mantonovic this task is finished, can you close it?
