### ISSUE TITLE
Layer fields visibility error

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#40]
The configuration done in the settings > Editor > Stratigraphy form fields has no effect in the Editor, but only in the Viewer.

- [ ] Separate the configuration of the editor from the viewer by creating a new panel in settings > viewer > Stratigraphy form fields
- [ ] Fix the bug in the editor

**Comment by malihgh** [comment]
Some **Stratigraphy fields** remain to add to server + these two fields in Editor and Viewer are the same and even they are sink but we should create Viewer (that is new), separated from Editor.

**Comment by malihgh** [comment]
@mantonovic this task is finished, can you close it?
