### ISSUE TITLE
Description vs Geology description 

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#45]
Define if it is correct to have two description fields in editor > startigraphy > layer form

![image](https://user-images.githubusercontent.com/1797931/174638428-692b0def-d6c8-4ab3-80c1-f6678bab5f72.png)

**Comment by mantonovic** [comment]
@gysimichael please confirm if the field "Geology Description" shall be removed.

**Comment by gysimichael** [comment]
@mantonovic no, this should not be deleted, but renamed: 
Description -> Lithological description (see attribute list "description")
Geology description -> Facies description (see attribute list "layer_geology")

I think, if you already implemented the new attribute list, this should be updated automatically. For "geology description" it migth be usefull to change the attribute name to layer_facies_description.

**Comment by mantonovic** [comment]
Added new fields and renamed as asked

**Comment by malihgh** [comment]
![Screenshot 2022-07-11 at 17-57-17 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/178306523-a44952cc-b1a6-4d91-a8ab-360c634d27d5.png)
