### ISSUE TITLE
remove field elevation-completion

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#46]
Remove "Completion type" in casing and reference elevation with completion

![image](https://user-images.githubusercontent.com/1797931/174639009-501e5be2-a817-4e25-8613-f830d94f00e3.png)

**Comment by gysimichael** [comment]
@mantonovic please delete also "completion elevation" and "reference elevation"

**Comment by malihgh** [comment]
![Screenshot 2022-07-08 at 11-23-57 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/177961997-2ed9d294-44cf-477f-a313-f1392f08860f.png)

**Comment by malihgh** [comment]
@gysimichael You asked also for: 
- "spud date" why here, does not make sense and belongs to the borehole tab
	- a better label for this would be "start date completion"

We should change the translation too?

**Comment by gysimichael** [comment]
@malihgh spud date and finish date should be added in the layer, as each casing is installed seperate. Hence in this view, only ID, Name of completion, Date abandonment and Remarks should stay

**Comment by gysimichael** [comment]
@malihgh we can keep the +casing button; it is very unlikely, that you install two different casings, but why not keeping it, if it already exists

**Comment by gysimichael** [comment]
@malihgh just thinking, ID in the topsection also does not make sence. This should also be moved to the layer info like the rest, hence only Name of completion, Date abandonment and Remarks stays on this level

**Comment by malihgh** [comment]
![Screenshot 2022-07-11 at 11-35-09 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/178235082-5575a7cd-f264-4f00-bcc3-25831216ca9b.png)

**Comment by malihgh** [comment]
![Screenshot 2022-07-11 at 19-23-56 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/178322483-dfca5774-7b0b-4880-89b7-1e7fa7405202.png)

**Comment by gysimichael** [comment]
@malihgh have you already included ID in this? On the screenshot, this is still missing.

**Comment by gysimichael** [comment]
ID should be above Top MD [m]
