### ISSUE TITLE
New editor fields

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#47]
In location:
Add new fields under Elevation (masl): 
- Reference elevation (number)
- Type of reference elevation (drop down>> see casing / Reference elevation)

In casing:
- In casing, change spud date to "Start date"
- change finish data to finish data casing

**Comment by gysimichael** [comment]
@mantonovic it should be labled "Start date completion"

**Comment by malihgh** [comment]
Add new fields to Location.
![Screenshot 2022-07-12 at 14-16-23 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/178487616-e370c846-f026-4ea1-b287-b48867987d69.png)

**Comment by malihgh** [comment]
@gysimichael Type of fields is ok? Can you give me the schema it is exist. If you want, I can also change the order of fields to be matched and more beautiful.

**Comment by gysimichael** [comment]
@malihgh looks good to me. Under Reference elevation type, the dropdown should be ibor117:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/U80864~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/U80864~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



20117001 | ibor117 | OKT | Oberkante Terrain |   | niveau du terrain |   | quota livello del terreno |   | ground surface
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
20117002 | ibor117 | ROK | Rohroberkante |   | bord supérieur du tubage |   | quota superiore della tubazione |   | casing top
20117003 | ibor117 | ROT | Rotary Table |   | rotary table |   | tavola rotary |   | rotary table
30000013 |   | KB | Kelly Bushing |   | kelly bushing |   | kelly bushing |   | kelly bushing
20117004 | ibor117 | SD | Schachtdeckel |   | couvercle de regard |   | tombino di protezione del pozzo |   | manhole cover
20117005 | ibor117 | a | anderes |   | autre |   | altro |   | other
20117006 | ibor117 | kA | keine Angaben |   | sans indication |   | senza indicazioni |   | not specified



</body>

</html>

this is something I cannot check from the screenshot. Otherwiese all good.

**Comment by gysimichael** [comment]
@malihgh "+/- Reference Elevation [m]" elevation should be small, can that be corrected to be consistent with the rest? That is my mistake, I've missed that in the attribute list

Annother mistake is "high reference system", that should be "hight reference system". This should also be corrected. Also something I've missed in the list.
