### ISSUE TITLE
remove drilling method (casing)

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#48]
casing > in list > remove drilling method + add inner + add outer

**Comment by malihgh** [comment]
@gysimichael  Should I add **inner** and *outer** to the names of these options? Are they numbers or text or dropdown or something else?

**Comment by gysimichael** [comment]
no.
drilling method should be deletet completely
new entrie field for inner diameter (added in the attribute liste see at the end of the list)
new entrie field for outer diameter (added in the attribute liste see at the end of the list)

**Comment by gysimichael** [comment]
they both are numbers in mm

**Comment by malihgh** [comment]
@mantonovic  Can you add **Inner diameter (mm)** and **Outer diameter (mm)** to translation and add these variables to DB so I can send them to the server?

**Comment by malihgh** [comment]
![Screenshot 2022-07-11 at 19-23-56 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/178322450-8bee2538-97b6-43cf-a28e-cfad56cf9784.png)

**Comment by malihgh** [comment]
![Screenshot 2022-07-18 at 11-42-55 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/179485693-efefaeda-a027-43cc-8a6c-6fa3ff5426a9.png)
