### ISSUE TITLE
add instrument option (casing)

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#49]
instrument >casing list > Add "No casing" option + permit to reset the selection (clear-able)

**Comment by gysimichael** [comment]
@malihgh as discussed in Teams, in the drop down under Casing, there should be at least one entrie called "open hole" "foro scoperto" "trou overt" "offenes Bohrloch"
This means, there is no completion installed, but still you can install an instrument into the borehole.

If there will be a completion installation, the the drop down should include the casings registered under casing

**Comment by malihgh** [comment]
@gysimichael Can you give me translations for "no casing"?

**Comment by malihgh** [comment]
@mantonovic this task is finished, you can close it.
