### ISSUE TITLE
country, canton and city read only

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#51]
Can't be changed by user. It is based on selected coordinates.

- [ ] Shall update automatically also when changing coordinates by hand.
- [ ] remove the address field
- [ ] delete land use

**Comment by gysimichael** [comment]
@mantonovic  though it would be important to write this information into the database. In case you do an export, this information can also be delivered

**Comment by malihgh** [comment]
![Screenshot 2022-07-12 at 14-16-23 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/178490014-1e9068dc-8eba-4672-bb5b-3e4944019d9b.png)

**Comment by gysimichael** [comment]
well done
