### ISSUE TITLE
Limit casing to 1

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#52]
Limit to create only one casing per borehole.

**Comment by malihgh** [comment]
![Screenshot 2022-07-06 at 17-18-10 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/177585641-e84be426-abf2-4bfb-b5c5-df65527a0c8f.png)

**Comment by malihgh** [comment]
@gysimichael  I limit casing to one, but in this case, the casing list in Instrument(issue #49), casing list in Filling(that we had planned to add #50), even showing a list of casing in Instrument, have no meaning. what should I do?

![photo_2022-07-08_10-15-00](https://user-images.githubusercontent.com/59393770/177948580-99446022-abf1-432b-b33d-219cb9586f8f.jpg)

**Comment by gysimichael** [comment]
@malihgh see comment on issue #49
