### ISSUE TITLE
Move drilling type

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#53]
Move drilling type from location to borehole.

@malihgh can you explain issue 15: 
 > add layers like casing

**Comment by malihgh** [comment]
Remove drilling type from Location page. 

![Screenshot 2022-07-06 at 16-24-24 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/177573708-da27b15e-ceb9-4fc6-a1a7-4f7832ce3dba.png)

**Comment by malihgh** [comment]
Add drilling type for Borehole

**Comment by malihgh** [comment]
@gysimichael Everything is ok?

**Comment by gysimichael** [comment]
Drilling type should be first, then drilling methode, then drilling purpose, then cuttings (cuttings should be labled borehole cuttings/core, though this should be fixed implementing the corrected apptribute list (see list I've sent you by mail)).
Then there should be a field called "Spud date" (see attribute list at the bottom) followed by "Drill end date"

**Comment by malihgh** [comment]
I build the page as your request. 
![Screenshot 2022-07-07 at 11-42-19 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/177744628-ba60a530-000f-4ebf-a5de-354781e7f1d9.png)

**Comment by malihgh** [comment]
@mantonovic  Can you translate **Purpose** to *Drilling purpose* + **Cutting** to *Borehole cutting/core* + add **Spud time** to translation and create a variable in DB so I can change the code for update  Spud time and send it to server.

**Comment by malihgh** [comment]
@gysimichael In *_06_Editor Mode Borehole page* file, I found :

- There needs to be an additional sublayer that specifies the different diameter sections, where as well the drilling method per section can be specified
- "Spud Date" entry missing
- "Top Bedrock TVD (m)" is missing	
- "+/- Top bedrock TVD [m]" is missing

Can you explain the first one and where I should add the two variables that remained?

**Comment by malihgh** [comment]
@gysimichael  I add "Top Bedrock TVD (m)" and "+/- Top bedrock TVD [m]", the place is good?

![Screenshot 2022-07-07 at 15-06-49 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/177780940-f16351cc-1742-4c4c-b302-10899fc3325c.png)

**Comment by malihgh** [comment]
![Screenshot 2022-07-22 at 09-47-00 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/180390594-92a6ff84-803a-4214-b5c2-6900e90204da.png)

**Comment by gysimichael** [comment]
@malihgh looks geat! Thanks!
