### ISSUE TITLE
the red strip is not visible enough

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/web-bdms#59]
When a layer is selected, the red strip is not visible enough, would be good to highlight the active layer in grey, as it is done in other layers

**Comment by malihgh** [comment]
I solved this issue before, can you close it?

![Screenshot 2022-07-27 at 17-25-28 Boreholes of Switzerland](https://user-images.githubusercontent.com/59393770/181286717-ffbd5e28-85a3-45f1-984f-3e4c933d6943.png)
